/**
 * ملف تحديث المنتجات بالبيانات الحقيقية
 * يتضمن 91 منتج بالأسعار والروابط الأصلية من كشف نجوم دلتا
 */

export const productsData = [
  {
    id: 1,
    nameAr: 'تفاح سكري',
    nameEn: 'Apple Gala 1000 G',
    price: 7,
    unit: 'Kg',
    imageUrl: 'https://lh3.googleusercontent.com/d/14raaz2yPcxGv4PLTCxyA2SqNDXJikXoi=w500',
    driveLink: 'https://drive.google.com/file/d/14raaz2yPcxGv4PLTCxyA2SqNDXJikXoi/view?usp=drivesdk',
    categoryAr: 'فواكه طازجة',
    categoryEn: 'Fresh Fruits',
  },
  {
    id: 2,
    nameAr: 'تفاح أخضر',
    nameEn: 'Apple Green 1000 G',
    price: 7,
    unit: 'Kg',
    imageUrl: 'https://lh3.googleusercontent.com/d/1x_4VWYYveuiwJtVdfNLReIithJO2JzGI=w500',
    driveLink: 'https://drive.google.com/file/d/1x_4VWYYveuiwJtVdfNLReIithJO2JzGI/view?usp=drivesdk',
    categoryAr: 'فواكه طازجة',
    categoryEn: 'Fresh Fruits',
  },
  {
    id: 3,
    nameAr: 'تفاح أحمر',
    nameEn: 'Apple Red 1000 G',
    price: 7.5,
    unit: 'Kg',
    imageUrl: 'https://lh3.googleusercontent.com/d/1s3WUV0dJ_3GYKa7_XV7BeTKfzl1iq__b=w500',
    driveLink: 'https://drive.google.com/file/d/1s3WUV0dJ_3GYKa7_XV7BeTKfzl1iq__b/view?usp=drivesdk',
    categoryAr: 'فواكه طازجة',
    categoryEn: 'Fresh Fruits',
  },
  {
    id: 4,
    nameAr: 'تفاح أصفر',
    nameEn: 'Apple Yellow 1000 G',
    price: 7,
    unit: 'Kg',
    imageUrl: 'https://lh3.googleusercontent.com/d/1JTO_fu2XlCN3-wFNV3OuN-SOPDgnGKUK=w500',
    driveLink: 'https://drive.google.com/file/d/1JTO_fu2XlCN3-wFNV3OuN-SOPDgnGKUK/view?usp=drivesdk',
    categoryAr: 'فواكه طازجة',
    categoryEn: 'Fresh Fruits',
  },
  {
    id: 5,
    nameAr: 'مشمش',
    nameEn: 'Apricot 1000 G',
    price: 16,
    unit: 'Kg',
    imageUrl: 'https://lh3.googleusercontent.com/d/1nGeZ4RDnJ-P-n30KM3JUgZFEy2hbHXE3=w500',
    driveLink: 'https://drive.google.com/file/d/1nGeZ4RDnJ-P-n30KM3JUgZFEy2hbHXE3/view?usp=drivesdk',
    categoryAr: 'فواكه طازجة',
    categoryEn: 'Fresh Fruits',
  },
  {
    id: 6,
    nameAr: 'كراث',
    nameEn: 'Arabic leeks (Kurath)',
    price: 1.5,
    unit: 'pc',
    imageUrl: 'https://lh3.googleusercontent.com/d/1bYMbxIhe8e1kSLSR24DCxhF9YCCBk5UX=w500',
    driveLink: 'https://drive.google.com/file/d/1bYMbxIhe8e1kSLSR24DCxhF9YCCBk5UX/view?usp=drivesdk',
    categoryAr: 'خضروات طازجة',
    categoryEn: 'Fresh Vegetables',
  },
  {
    id: 7,
    nameAr: 'موز',
    nameEn: 'Banana 1000 G',
    price: 6.5,
    unit: 'Kg',
    imageUrl: 'https://lh3.googleusercontent.com/d/1C4X6hYllVzFnei9q-pGR5ET3GzCmN8hc=w500',
    driveLink: 'https://drive.google.com/file/d/1C4X6hYllVzFnei9q-pGR5ET3GzCmN8hc/view?usp=drivesdk',
    categoryAr: 'فواكه طازجة',
    categoryEn: 'Fresh Fruits',
  },
  {
    id: 8,
    nameAr: 'فاصوليا خضراء',
    nameEn: 'Beans Green Fresh 1000 G',
    price: 8,
    unit: 'Kg',
    imageUrl: 'https://lh3.googleusercontent.com/d/1hOScKwXU6b7Z7xPVst4u3oBCHfTRbRGc=w500',
    driveLink: 'https://drive.google.com/file/d/1hOScKwXU6b7Z7xPVst4u3oBCHfTRbRGc/view?usp=drivesdk',
    categoryAr: 'خضروات طازجة',
    categoryEn: 'Fresh Vegetables',
  },
  {
    id: 9,
    nameAr: 'بنجر',
    nameEn: 'Beet Root Local 1000 G',
    price: 5,
    unit: 'Kg',
    imageUrl: 'https://lh3.googleusercontent.com/d/1t5GnOEdjJX6RB4E2gxUoTQ8ceEix_LLt=w500',
    driveLink: 'https://drive.google.com/file/d/1t5GnOEdjJX6RB4E2gxUoTQ8ceEix_LLt/view?usp=drivesdk',
    categoryAr: 'خضروات طازجة',
    categoryEn: 'Fresh Vegetables',
  },
  {
    id: 10,
    nameAr: 'رومي أخضر',
    nameEn: 'Bell Pepper Green 1000 G LOCAL',
    price: 6,
    unit: 'Kg',
    imageUrl: 'https://lh3.googleusercontent.com/d/1cw_hNecLBH1l-QqW26K18rR77Amz7hd3=w500',
    driveLink: 'https://drive.google.com/file/d/1cw_hNecLBH1l-QqW26K18rR77Amz7hd3/view?usp=drivesdk',
    categoryAr: 'خضروات طازجة',
    categoryEn: 'Fresh Vegetables',
  },
  {
    id: 11,
    nameAr: 'رومي أحمر',
    nameEn: 'Bell Pepper Red 1000 G LOCAL',
    price: 8,
    unit: 'Kg',
    imageUrl: 'https://lh3.googleusercontent.com/d/1g_Ymd4KHPMyhlgtJzUCVoxaCw8Qgk29_=w500',
    driveLink: 'https://drive.google.com/file/d/1g_Ymd4KHPMyhlgtJzUCVoxaCw8Qgk29_/view?usp=drivesdk',
    categoryAr: 'خضروات طازجة',
    categoryEn: 'Fresh Vegetables',
  },
  {
    id: 12,
    nameAr: 'رومي أصفر',
    nameEn: 'Bell pepper Yellow 1000 G LOCAL',
    price: 8,
    unit: 'Kg',
    imageUrl: 'https://lh3.googleusercontent.com/d/1HWgl4vQ7-yyD13LJH9Leyi7ZmOmZo8fb=w500',
    driveLink: 'https://drive.google.com/file/d/1HWgl4vQ7-yyD13LJH9Leyi7ZmOmZo8fb/view?usp=drivesdk',
    categoryAr: 'خضروات طازجة',
    categoryEn: 'Fresh Vegetables',
  },
  {
    id: 13,
    nameAr: 'كرلا',
    nameEn: 'Bitter Gourd (karela) 1000 G',
    price: 6.5,
    unit: 'Kg',
    imageUrl: 'https://lh3.googleusercontent.com/d/1NAapL0Lss9vg4VqST9-BbdmHZDZ3QChT=w500',
    driveLink: 'https://drive.google.com/file/d/1NAapL0Lss9vg4VqST9-BbdmHZDZ3QChT/view?usp=drivesdk',
    categoryAr: 'خضروات طازجة',
    categoryEn: 'Fresh Vegetables',
  },
  {
    id: 14,
    nameAr: 'بركلي',
    nameEn: 'Broccoli Local 1000 G',
    price: 16,
    unit: 'Kg',
    imageUrl: 'https://lh3.googleusercontent.com/d/1H1hPMaQrc4fHZJpypn8k3W8r1x4RPoOg=w500',
    driveLink: 'https://drive.google.com/file/d/1H1hPMaQrc4fHZJpypn8k3W8r1x4RPoOg/view?usp=drivesdk',
    categoryAr: 'خضروات طازجة',
    categoryEn: 'Fresh Vegetables',
  },
  {
    id: 15,
    nameAr: 'ملفوف أحمر',
    nameEn: 'Cabbage Red Local 1000 G',
    price: 4.5,
    unit: 'Kg',
    imageUrl: 'https://lh3.googleusercontent.com/d/1GmaS_f37r1vSWu_rrhSi71YWPH5I41Gr=w500',
    driveLink: 'https://drive.google.com/file/d/1GmaS_f37r1vSWu_rrhSi71YWPH5I41Gr/view?usp=drivesdk',
    categoryAr: 'خضروات طازجة',
    categoryEn: 'Fresh Vegetables',
  },
  {
    id: 16,
    nameAr: 'ملفوف أبيض',
    nameEn: 'Cabbage White Local 1000 G',
    price: 3.5,
    unit: 'Kg',
    imageUrl: 'https://lh3.googleusercontent.com/d/1yZGiLqEPln5Lk_nO5uuyLMdiegf0wZ8S=w500',
    driveLink: 'https://drive.google.com/file/d/1yZGiLqEPln5Lk_nO5uuyLMdiegf0wZ8S/view?usp=drivesdk',
    categoryAr: 'خضروات طازجة',
    categoryEn: 'Fresh Vegetables',
  },
  {
    id: 17,
    nameAr: 'تين شوكي',
    nameEn: 'Cactus Pears Seasonal Fruit KSA 1000 G',
    price: 13,
    unit: 'Kg',
    imageUrl: 'https://lh3.googleusercontent.com/d/1dt0lqZGWz7JdY5dYlR1tLaXA3VQADP61=w500',
    driveLink: 'https://drive.google.com/file/d/1dt0lqZGWz7JdY5dYlR1tLaXA3VQADP61/view?usp=drivesdk',
    categoryAr: 'فواكه طازجة',
    categoryEn: 'Fresh Fruits',
  },
  {
    id: 18,
    nameAr: 'جزر محلي',
    nameEn: 'Carrot 1000 G',
    price: 4.5,
    unit: 'Kg',
    imageUrl: 'https://lh3.googleusercontent.com/d/1qKdTHTwWcqymmJfubyR5iD2ZCXQATDdk=w500',
    driveLink: 'https://drive.google.com/file/d/1qKdTHTwWcqymmJfubyR5iD2ZCXQATDdk/view?usp=drivesdk',
    categoryAr: 'خضروات طازجة',
    categoryEn: 'Fresh Vegetables',
  },
  {
    id: 19,
    nameAr: 'زهرة',
    nameEn: 'Califlower 1000 G',
    price: 7,
    unit: 'Kg',
    imageUrl: 'https://lh3.googleusercontent.com/d/1-LRmks22xtvxe0-g8WMk17KJeGBLsYRV=w500',
    driveLink: 'https://drive.google.com/file/d/1-LRmks22xtvxe0-g8WMk17KJeGBLsYRV/view?usp=drivesdk',
    categoryAr: 'خضروات طازجة',
    categoryEn: 'Fresh Vegetables',
  },
  {
    id: 20,
    nameAr: 'كرفس محلي',
    nameEn: 'Celery Green Local 1000 G',
    price: 18,
    unit: 'Kg',
    imageUrl: 'https://lh3.googleusercontent.com/d/18t3pyZ33bNvPuKs65FV3kow14PIzVrg-=w500',
    driveLink: 'https://drive.google.com/file/d/18t3pyZ33bNvPuKs65FV3kow14PIzVrg-/view?usp=drivesdk',
    categoryAr: 'خضروات طازجة',
    categoryEn: 'Fresh Vegetables',
  },
];

/**
 * دالة تحويل رابط Google Drive إلى رابط صورة مباشر
 */
export function convertGoogleDriveLink(driveUrl: string): string {
  const fileIdMatch = driveUrl.match(/\/d\/([a-zA-Z0-9-_]+)/);
  if (fileIdMatch && fileIdMatch[1]) {
    return `https://lh3.googleusercontent.com/d/${fileIdMatch[1]}=w500`;
  }
  return driveUrl;
}

/**
 * دالة للحصول على جميع المنتجات بالبيانات المحدثة
 */
export function getUpdatedProducts() {
  return productsData.map(product => ({
    ...product,
    imageUrl: convertGoogleDriveLink(product.driveLink),
  }));
}

export default productsData;
